FROM python:3.11-slim

WORKDIR /

RUN pip install --upgrade pip

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["python", "manage.py", "migrate"]

CMD ["python", "manage.py", "fill_database"]

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
